name: credisense
description: Credisense - Credit risk frontend prototype
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.19.0
  google_fonts: ^4.0.4
  fl_chart: ^0.66.2
  http: ^0.13.6
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: Noto Sans Devanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
        - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
          weight: 700
    - family: Noto Sans Tamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
        - asset: assets/fonts/NotoSansTamil-Bold.ttf
          weight: 700
    - family: Noto Sans Telugu
      fonts:
        - asset: assets/fonts/NotoSansTelugu-Regular.ttf
        - asset: assets/fonts/NotoSansTelugu-Bold.ttf
          weight: 700
    - family: Noto Sans Kannada
      fonts:
        - asset: assets/fonts/NotoSansKannada-Regular.ttf
        - asset: assets/fonts/NotoSansKannada-Bold.ttf
          weight: 700
    - family: Noto Sans Malayalam
      fonts:
        - asset: assets/fonts/NotoSansMalayalam-Regular.ttf
        - asset: assets/fonts/NotoSansMalayalam-Bold.ttf
          weight: 700
    - family: Noto Sans Bengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700
  
  assets:
    - assets/mock_transactions.json
    - assets/mock_persona.json
