// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzpriPh5Q3oKLHl_V-fZFA6Ja6moXE7iw',
    appId: '1:961614869999:web:65c4f5c966cb2e7234b21a',
    messagingSenderId: '961614869999',
    projectId: 'credisense',
    authDomain: 'credisense.firebaseapp.com',
    storageBucket: 'credisense.firebasestorage.app',
    measurementId: 'G-77GDC24ZV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSuPJfL_EtsmVUOP2hsZ8KQG7nueYp7A',
    appId: '1:961614869999:android:2585eae12b7a8ae434b21a',
    messagingSenderId: '961614869999',
    projectId: 'credisense',
    storageBucket: 'credisense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ2P1jHZLKGq1I3pV06wcs8NjVLXwe3sw',
    appId: '1:961614869999:ios:e2075e8ddd3a72ef34b21a',
    messagingSenderId: '961614869999',
    projectId: 'credisense',
    storageBucket: 'credisense.firebasestorage.app',
    iosBundleId: 'com.example.credisense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ2P1jHZLKGq1I3pV06wcs8NjVLXwe3sw',
    appId: '1:961614869999:ios:e2075e8ddd3a72ef34b21a',
    messagingSenderId: '961614869999',
    projectId: 'credisense',
    storageBucket: 'credisense.firebasestorage.app',
    iosBundleId: 'com.example.credisense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzpriPh5Q3oKLHl_V-fZFA6Ja6moXE7iw',
    appId: '1:961614869999:web:6956436587ffc31034b21a',
    messagingSenderId: '961614869999',
    projectId: 'credisense',
    authDomain: 'credisense.firebaseapp.com',
    storageBucket: 'credisense.firebasestorage.app',
    measurementId: 'G-V74V1MF8J3',
  );
}
