import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart'; // ✅ Add this
import 'app.dart';
import 'providers/auth_provider.dart';
import 'providers/finance_provider.dart';
import 'providers/theme_provider.dart';
import 'services/mock_service.dart';
import 'firebase_options.dart'; // ✅ Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final mockService = MockService();
  await mockService.loadMockData();

  runApp(
    MultiProvider(
      providers: [
        Provider<MockService>.value(value: mockService),
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => FinanceProvider(mockService)),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
      ],
      child: const CredisenseApp(),
    ),
  );
}
